version: "3.3"
services:
  contact-form-nodejs:
    container_name: contact-form-nodejs
    network_mode: host
    build: .
    volumes:
      - ./storage:/app/storage
    #environment:
      #- WEB_ADRESS=https://example.com
      #- SITE_NAME=Site Name
      #- SITE_PHONE=+32 20321 103281
      #- SITE_ADRESS=PARIS
      #- SITE_EMAIL=info@exemple.be

      #- OPENID_USE=false
      #- OPENID_LOGIN_ADRESS=https://login.exemple.com

      #- MAP_LATITUDE=0.000
      #- MAP_LONGITUDE=0.000
      #- MAPBOX_TOKEN=<your-mapbox-token-here>
      #- SMTP_HOST=smtp.exemple.com
      #- SMTP_PORT=465
      #- SMTP_USER=info@exemple.com
      #- SMTP_PASSWORD=<password>

      #- MAIL_FROM=info@exemple.com
      #- MAIL_TO=test@exemple.com
      #- MAIL_SUBJECT=Test
